name: attrguide-breast
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - pytorch-cuda=12.1
  - numpy
  - pandas
  - pillow
  - scikit-learn
  - tqdm
  - pip
  - pip:
      - wandb
      - ftfy
      - regex
      - git+https://github.com/openai/CLIP.git

